### ISSUE TITLE
fatal request timeout

### ISSUE THREAD

**Issue by shuninglu** [lluisrojass/Tumblr-Post-Scraper#2]

**Comment by lluisrojass** [comment]
could you provide more details? @juri-220

**Comment by humanenver** [comment]
same problem
when I insert a blog name , i get that error: fatal request timeout

**Comment by lluisrojass** [comment]
@humanenver could you provide more details? 

1. does it happen everytime you try to scrape or does this only occur on certain occasions? 
2. Timeouts like this sometimes happen after a scrape continues for a lengthy duration, i've found these to be usually due to tumblr's internal rate-limiting precautions. 
3. does it consistently happen on one blog?

**Comment by humanenver** [comment]
1. It happens all the time

does this program have any dependencies . Also our university uses a proxy
